name: jaydipbaraiya
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  timelines: ^0.1.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/documents/

  fonts:
    - family: SourceSans3-Bold
      fonts:
        - asset: assets/fonts/SourceSans3-Bold.ttf

    - family: SourceSans3-Medium
      fonts:
        - asset: assets/fonts/SourceSans3-Medium.ttf

    - family: SourceSans3-Regular
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  image_path: "assets/images/icon3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon3.png"
    background_color:
    theme_color: