name: jaydipbaraiya
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/documents/

  fonts:
    - family: SourceSans3-Bold
      fonts:
        - asset: assets/fonts/SourceSans3-Bold.ttf

    - family: SourceSans3-Regular
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

